dabaigta pertvarkyt struktūra

diff --git a/.github/workflows/API_deploy.yml b/.github/workflows/API_deploy.yml
--- a/.github/workflows/API_deploy.yml
+++ b/.github/workflows/API_deploy.yml
@@ -26,4 +26,32 @@ jobs:
             - name: Checkout code
               uses: actions/checkout@v3
 
-            - name: 
+            - name: Create SSH directory
+              run: mkdir -p ~/.ssh
+
+            - name: Add host to known hosts
+              run: ssh-keyscan -H 3.73.178.155 > ~/.ssh/known_hosts
+
+            - name: Check and install Ansible
+              run: |
+                if ! command -v ansible &> /dev/null; then
+                  echo "Ansible not found. Installing..."
+                  sudo apt-get update && sudo apt-get install -y ansible
+                else
+                  echo "Ansible already installed"
+                fi
+
+            - name: Ensure everything is up to date
+              run: |
+                sudo dpkg --configure -a
+                sudo apt-get update --fix-missing
+                sudo apt-get -f install
+
+            - name: Setup SSH key to connect to EC2 VM
+              run: |
+                mkdir -p ~/.ssh
+                echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
+                chmod 600 ~/.ssh/id_rsa
+
+            - name: Run the playbook to deploy the API
+              run: ansible-playbook -u ubuntu -i 3.73.178.155, --private-key ~/.ssh/id_rsa API_on_docker_on_vm.yml
